### ISSUE TITLE
NPathComplexity PMD rule violation

### ISSUE THREAD

**Issue by emurova** [hashgraph/did-sdk-java#19]
**Detailed Description**
PMD rule violations when running gradle build for did-sdk-java.

**Actual Behavior**
Run gradle build

**Expected Behavior**
No PMD rule violations.

**Environment:**
- Java: corretto-11.0.13
- OS: macOS Big Sur 
- Version: 11.6
- IDE: IntelliJ IDEA 2021.3 (Community Edition)

**Additional Context**
<img width="731" alt="Screen Shot 2021-12-22 at 2 02 07 pm" src="https://user-images.githubusercontent.com/43060587/147029771-9599de21-797e-4b2d-b459-37d44bedf7a0.png">

**Comment by emurova** [comment]
Im happy to fix it but dont have a permission to push a branch.

**Comment by tim-mchale** [comment]
Issue resolved by last merge
